Thick sample
TuragaLab/chromatix pull request #77
Opened 2023-03-06 05:02 UTC by isildur7

Added a multislice thick sample

Added a method for precalculating propagators outside

Should we modify the exact_propagation functions to be able to take a propagator?

2023-03-06 14:11 UTC, diptodip requested changes
Could you implement passing the propagator as an option to exact_propagate?

Inside `exact_propagate` it should look something like 

```python
if propagator is None:
    propagator = calculate_exact_propagator(...)
```
so that the current behavior stays the same if we don't pass the propagator.

And then in the `Propagate` element, we can precompute the propagator during setup and pass it to the propagation function as needed. So eventually we should do this for `transfer_propagate` as well.

I'm happy to make these changes myself.

2023-03-06 14:11 UTC, diptodip commented on src/chromatix/functional/propagation.py
> +    """Calculate a proapgator which can be used in the exact propagate method.
proapgator -> propagator

2023-03-06 14:11 UTC, diptodip commented on src/chromatix/functional/samples.py
> +        # Propagating field
Could we pass the calculated propagator to exact_propagate here?

2023-03-06 17:12 UTC, isildur7 commented
I will implement it for transfer_propagate as well, in another PR soon.

2023-03-06 19:33 UTC, diptodip reviewed
So of course it mostly looks good, we just have to nail down exactly how we want the custom propagator arguments handled in https://github.com/TuragaLab/chromatix/discussions/78

2023-03-06 19:33 UTC, diptodip commented on src/chromatix/functional/samples.py
> +    half_stack_thikness = thickness_per_slice * absorption_stack.shape[0] / 2
`half_stack_thikness -> half_stack_thickness`

2023-03-06 19:33 UTC, diptodip commented on src/chromatix/functional/samples.py
> +        z=-half_stack_thikness,
And here

2023-03-06 19:42 UTC, diptodip commented
But once those little typos are fixed I'm happy to accept this one and then fix the custom propagator stuff in another PR.

2023-03-07 14:54 UTC, diptodip approved these changes

2023-03-07 14:55 UTC, merged